[2022-03-20 12:10:07,387] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-02-12T00:00:00+00:00 [queued]>
[2022-03-20 12:10:07,421] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-02-12T00:00:00+00:00 [queued]>
[2022-03-20 12:10:07,422] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:10:07,422] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 12:10:07,422] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:10:07,482] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-02-12T00:00:00+00:00
[2022-03-20 12:10:07,486] {standard_task_runner.py:52} INFO - Started process 41735 to run task
[2022-03-20 12:10:07,504] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-02-12T00:00:00+00:00', '--job-id', '248', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpwh_zvnme', '--error-file', '/tmp/tmp45n06bcn']
[2022-03-20 12:10:07,505] {standard_task_runner.py:77} INFO - Job 248: Subtask is_api_available
[2022-03-20 12:10:07,641] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-02-12T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 12:10:07,838] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-02-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-12T00:00:00+00:00
[2022-03-20 12:10:07,839] {http.py:101} INFO - Poking: api/
[2022-03-20 12:10:07,849] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 12:10:07,856] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 12:10:08,400] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 12:10:08,414] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200212T000000, start_date=20220320T121007, end_date=20220320T121008
[2022-03-20 12:10:08,515] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 12:10:08,524] {local_task_job.py:151} INFO - Task exited with return code 0
