[2022-03-20 08:23:35,997] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 08:23:36,050] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 08:23:36,054] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 08:23:36,064] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 08:23:36,065] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 08:23:36,124] {taskinstance.py:1087} INFO - Executing <Task(SqliteOperator): creating_table> on 2022-03-19T00:00:00+00:00
[2022-03-20 08:23:36,146] {standard_task_runner.py:52} INFO - Started process 2139 to run task
[2022-03-20 08:23:36,263] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'creating_table', '2022-03-19T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp2l6qvu59', '--error-file', '/tmp/tmpcgsi17h3']
[2022-03-20 08:23:36,268] {standard_task_runner.py:77} INFO - Job 5: Subtask creating_table
[2022-03-20 08:23:36,569] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.creating_table 2022-03-19T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 08:23:36,809] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-19T00:00:00+00:00
[2022-03-20 08:23:36,810] {sqlite.py:63} INFO - Executing: 
                CREATE TABLE users(
                    firstname text not null,
                    lastname TEXT NOT NULL,
                    country TEXT NOT NULL,
                    username TEXT NOT NULL,
                    password TEXT NOT NULL,
                    email TEXT NOT NULL PRIMARY KEY
                );
            
[2022-03-20 08:23:36,827] {base.py:69} INFO - Using connection to: id: db_sqlite. Host: /home/airflow/airflow/airflow.db, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 08:23:36,833] {dbapi.py:204} INFO - Running statement: 
                CREATE TABLE users(
                    firstname text not null,
                    lastname TEXT NOT NULL,
                    country TEXT NOT NULL,
                    username TEXT NOT NULL,
                    password TEXT NOT NULL,
                    email TEXT NOT NULL PRIMARY KEY
                );
            , parameters: []
[2022-03-20 08:23:36,835] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/providers/sqlite/operators/sqlite.py", line 65, in execute
    hook.run(self.sql, parameters=self.parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: table users already exists
[2022-03-20 08:23:36,892] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=user_processing, task_id=creating_table, execution_date=20220319T000000, start_date=20220320T082336, end_date=20220320T082336
[2022-03-20 08:23:36,971] {local_task_job.py:151} INFO - Task exited with return code 1
