[2022-03-20 13:59:55,944] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-09T00:00:00+00:00 [queued]>
[2022-03-20 13:59:55,964] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-09T00:00:00+00:00 [queued]>
[2022-03-20 13:59:55,965] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 13:59:55,965] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2022-03-20 13:59:55,965] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 13:59:56,013] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-09T00:00:00+00:00
[2022-03-20 13:59:56,017] {standard_task_runner.py:52} INFO - Started process 96657 to run task
[2022-03-20 13:59:56,034] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-09T00:00:00+00:00', '--job-id', '893', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp76zfiqb2', '--error-file', '/tmp/tmpwxwo77ai']
[2022-03-20 13:59:56,035] {standard_task_runner.py:77} INFO - Job 893: Subtask is_api_available
[2022-03-20 13:59:56,166] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-09T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 13:59:56,640] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-09T00:00:00+00:00
[2022-03-20 13:59:56,640] {http.py:101} INFO - Poking: api/
[2022-03-20 13:59:56,652] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 13:59:56,655] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 13:59:57,419] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 13:59:57,429] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200109T000000, start_date=20220320T135955, end_date=20220320T135957
[2022-03-20 13:59:57,516] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 13:59:57,538] {local_task_job.py:151} INFO - Task exited with return code 0
