[2022-03-20 12:02:58,902] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-28T00:00:00+00:00 [queued]>
[2022-03-20 12:02:58,915] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-28T00:00:00+00:00 [queued]>
[2022-03-20 12:02:58,915] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:02:58,916] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 12:02:58,916] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:02:58,958] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-28T00:00:00+00:00
[2022-03-20 12:02:58,964] {standard_task_runner.py:52} INFO - Started process 36341 to run task
[2022-03-20 12:02:58,985] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-28T00:00:00+00:00', '--job-id', '173', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpm74sbado', '--error-file', '/tmp/tmp6qy61r5m']
[2022-03-20 12:02:58,987] {standard_task_runner.py:77} INFO - Job 173: Subtask is_api_available
[2022-03-20 12:02:59,134] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-28T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 12:02:59,317] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-28T00:00:00+00:00
[2022-03-20 12:02:59,318] {http.py:101} INFO - Poking: api/
[2022-03-20 12:02:59,329] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 12:02:59,334] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 12:02:59,855] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 12:02:59,873] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200128T000000, start_date=20220320T120258, end_date=20220320T120259
[2022-03-20 12:02:59,965] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 12:02:59,980] {local_task_job.py:151} INFO - Task exited with return code 0
