[2022-03-20 13:59:37,784] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-06T00:00:00+00:00 [queued]>
[2022-03-20 13:59:37,806] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-06T00:00:00+00:00 [queued]>
[2022-03-20 13:59:37,806] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 13:59:37,806] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2022-03-20 13:59:37,807] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 13:59:37,854] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-06T00:00:00+00:00
[2022-03-20 13:59:37,860] {standard_task_runner.py:52} INFO - Started process 96504 to run task
[2022-03-20 13:59:37,878] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-06T00:00:00+00:00', '--job-id', '890', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp3363q0rn', '--error-file', '/tmp/tmpz45oftzw']
[2022-03-20 13:59:37,879] {standard_task_runner.py:77} INFO - Job 890: Subtask is_api_available
[2022-03-20 13:59:38,023] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-06T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 13:59:38,371] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-06T00:00:00+00:00
[2022-03-20 13:59:38,372] {http.py:101} INFO - Poking: api/
[2022-03-20 13:59:38,386] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 13:59:38,391] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 13:59:38,868] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 13:59:38,879] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200106T000000, start_date=20220320T135937, end_date=20220320T135938
[2022-03-20 13:59:38,973] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 13:59:39,023] {local_task_job.py:151} INFO - Task exited with return code 0
