[2022-03-21 05:12:37,494] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2020-01-19T00:00:00+00:00 [queued]>
[2022-03-21 05:12:37,512] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.storing_user 2020-01-19T00:00:00+00:00 [queued]>
[2022-03-21 05:12:37,512] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 05:12:37,512] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2022-03-21 05:12:37,512] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 05:12:37,555] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): storing_user> on 2020-01-19T00:00:00+00:00
[2022-03-21 05:12:37,560] {standard_task_runner.py:52} INFO - Started process 7067 to run task
[2022-03-21 05:12:37,579] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'storing_user', '2020-01-19T00:00:00+00:00', '--job-id', '1094', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp95kqth_u', '--error-file', '/tmp/tmpjhjnxibz']
[2022-03-21 05:12:37,580] {standard_task_runner.py:77} INFO - Job 1094: Subtask storing_user
[2022-03-21 05:12:37,714] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.storing_user 2020-01-19T00:00:00+00:00 [running]> on host airflowvm
[2022-03-21 05:12:37,953] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=storing_user
AIRFLOW_CTX_EXECUTION_DATE=2020-01-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-19T00:00:00+00:00
[2022-03-21 05:12:37,954] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 05:12:37,955] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo -e ".separator ","\n. import /tmp/processed_user.csv users" | sqlite3 /home/airflow/airflow/airflow.db']
[2022-03-21 05:12:37,972] {subprocess.py:75} INFO - Output:
[2022-03-21 05:12:37,988] {subprocess.py:79} INFO - /tmp/processed_user.csv:1: INSERT failed: UNIQUE constraint failed: users.email
[2022-03-21 05:12:37,990] {subprocess.py:83} INFO - Command exited with return code 1
[2022-03-21 05:12:38,009] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-21 05:12:38,020] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=user_processing, task_id=storing_user, execution_date=20200119T000000, start_date=20220321T051237, end_date=20220321T051238
[2022-03-21 05:12:38,088] {local_task_job.py:151} INFO - Task exited with return code 1
