[2022-03-20 11:52:35,821] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-07T00:00:00+00:00 [queued]>
[2022-03-20 11:52:35,838] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-01-07T00:00:00+00:00 [queued]>
[2022-03-20 11:52:35,839] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 11:52:35,839] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 11:52:35,839] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 11:52:35,880] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-01-07T00:00:00+00:00
[2022-03-20 11:52:35,884] {standard_task_runner.py:52} INFO - Started process 28501 to run task
[2022-03-20 11:52:35,902] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-01-07T00:00:00+00:00', '--job-id', '68', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp24ghkv5f', '--error-file', '/tmp/tmpd9pqkvhz']
[2022-03-20 11:52:35,904] {standard_task_runner.py:77} INFO - Job 68: Subtask is_api_available
[2022-03-20 11:52:36,021] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-01-07T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 11:52:36,131] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-01-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-07T00:00:00+00:00
[2022-03-20 11:52:36,132] {http.py:101} INFO - Poking: api/
[2022-03-20 11:52:36,141] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 11:52:36,146] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 11:52:36,564] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 11:52:36,587] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200107T000000, start_date=20220320T115235, end_date=20220320T115236
[2022-03-20 11:52:36,670] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 11:52:36,693] {local_task_job.py:151} INFO - Task exited with return code 0
