[2022-03-20 12:54:35,919] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-01-22T00:00:00+00:00 [queued]>
[2022-03-20 12:54:35,937] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-01-22T00:00:00+00:00 [queued]>
[2022-03-20 12:54:35,937] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:54:35,937] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 12:54:35,937] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:54:36,057] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-22T00:00:00+00:00
[2022-03-20 12:54:36,076] {standard_task_runner.py:52} INFO - Started process 66671 to run task
[2022-03-20 12:54:36,086] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2022-01-22T00:00:00+00:00', '--job-id', '498', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpw3_ojwa7', '--error-file', '/tmp/tmp847n244b']
[2022-03-20 12:54:36,087] {standard_task_runner.py:77} INFO - Job 498: Subtask is_api_available
[2022-03-20 12:54:36,204] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2022-01-22T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 12:54:36,369] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-22T00:00:00+00:00
[2022-03-20 12:54:36,370] {http.py:101} INFO - Poking: api/
[2022-03-20 12:54:36,381] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 12:54:36,385] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 12:54:36,910] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 12:54:36,918] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220122T000000, start_date=20220320T125435, end_date=20220320T125436
[2022-03-20 12:54:37,071] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 12:54:37,101] {local_task_job.py:151} INFO - Task exited with return code 0
