[2022-03-20 13:56:25,684] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-02-02T00:00:00+00:00 [queued]>
[2022-03-20 13:56:25,769] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-02-02T00:00:00+00:00 [queued]>
[2022-03-20 13:56:25,778] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 13:56:25,783] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2022-03-20 13:56:25,783] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 13:56:25,863] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-02-02T00:00:00+00:00
[2022-03-20 13:56:25,886] {standard_task_runner.py:52} INFO - Started process 94650 to run task
[2022-03-20 13:56:25,991] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-02-02T00:00:00+00:00', '--job-id', '867', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp8rvx9lba', '--error-file', '/tmp/tmpro4718gi']
[2022-03-20 13:56:25,993] {standard_task_runner.py:77} INFO - Job 867: Subtask is_api_available
[2022-03-20 13:56:26,375] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-02-02T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 13:56:26,573] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T00:00:00+00:00
[2022-03-20 13:56:26,574] {http.py:101} INFO - Poking: api/
[2022-03-20 13:56:26,584] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 13:56:26,589] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 13:56:27,064] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 13:56:27,080] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200202T000000, start_date=20220320T135625, end_date=20220320T135627
[2022-03-20 13:56:27,171] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 13:56:27,192] {local_task_job.py:151} INFO - Task exited with return code 0
