[2022-03-20 12:46:09,360] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-01-06T00:00:00+00:00 [queued]>
[2022-03-20 12:46:09,375] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-01-06T00:00:00+00:00 [queued]>
[2022-03-20 12:46:09,375] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:46:09,376] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 12:46:09,376] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:46:09,574] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-06T00:00:00+00:00
[2022-03-20 12:46:09,579] {standard_task_runner.py:52} INFO - Started process 62765 to run task
[2022-03-20 12:46:09,603] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2022-01-06T00:00:00+00:00', '--job-id', '418', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpylmktbml', '--error-file', '/tmp/tmpeewfh8jw']
[2022-03-20 12:46:09,609] {standard_task_runner.py:77} INFO - Job 418: Subtask is_api_available
[2022-03-20 12:46:09,942] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2022-01-06T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 12:46:10,432] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-06T00:00:00+00:00
[2022-03-20 12:46:10,433] {http.py:101} INFO - Poking: api/
[2022-03-20 12:46:10,447] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 12:46:10,451] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 12:46:10,989] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 12:46:10,999] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220106T000000, start_date=20220320T124609, end_date=20220320T124610
[2022-03-20 12:46:11,364] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 12:46:11,407] {local_task_job.py:151} INFO - Task exited with return code 0
