[2022-03-20 12:16:42,293] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-02-26T00:00:00+00:00 [queued]>
[2022-03-20 12:16:42,315] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2020-02-26T00:00:00+00:00 [queued]>
[2022-03-20 12:16:42,323] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:16:42,323] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-20 12:16:42,323] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 12:16:42,384] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2020-02-26T00:00:00+00:00
[2022-03-20 12:16:42,389] {standard_task_runner.py:52} INFO - Started process 46670 to run task
[2022-03-20 12:16:42,421] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2020-02-26T00:00:00+00:00', '--job-id', '318', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp784k2hx3', '--error-file', '/tmp/tmpa3dqytmv']
[2022-03-20 12:16:42,429] {standard_task_runner.py:77} INFO - Job 318: Subtask is_api_available
[2022-03-20 12:16:42,610] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2020-02-26T00:00:00+00:00 [running]> on host airflowvm
[2022-03-20 12:16:42,787] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2020-02-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-26T00:00:00+00:00
[2022-03-20 12:16:42,788] {http.py:101} INFO - Poking: api/
[2022-03-20 12:16:42,799] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: ***, extra: {}
[2022-03-20 12:16:42,803] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-20 12:16:43,436] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-20 12:16:43,453] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20200226T000000, start_date=20220320T121642, end_date=20220320T121643
[2022-03-20 12:16:43,571] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 12:16:43,621] {local_task_job.py:151} INFO - Task exited with return code 0
